- name: Push aci_model

  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  block:
  - name: Add a tenant using a JSON string
    connection: local
    aci_rest:
      <<: *aci_login
      path: /api/mo/uni/tn-[Gaetano].json
      method: post
      content: |
       {
         "fvTenant": {
           "attributes": {
             "name": "Gaetano",
             "descr": "Gaetano ansible"
           }
         }
       }

  - name: Add physical domains
    connection: local
    aci_rest:
      <<: *aci_login
      path: /api/node/mo/uni/phys-{{ item.access_policy_physical_domain_name }}.json
      method: post
      content: |
       {
         "physDomP": {
           "attributes": {
             "dn":"uni/phys-{{  item.access_policy_physical_domain_name }}",
             "name":"{{ item.access_policy_physical_domain_name }}",
             "ownerKey":"",
             "ownerTag":""
           },
           "children":[{
             "infraRsVlanNs": {
               "attributes":{
                 "tDn":"uni/infra/vlanns-[{{ item.access_policy_physical_domain_vlan_pool }}]-{{ item.access_policy_physical_domain_vlan_pool_alloc }}"
               }
             }
           }]
         }
       }
    with_items: '{{ aci_model_data|aci_listify("access_policy","physical_domain") }}'

  - name: Who am i
    shell: "whoami"
    register: results
 
  - name: show results
    debug: msg={{ results.stdout_lines }}


