- name: Push aci_model

  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  block:
  - name: Query all AEPs
    aci_aep:
      <<: *aci_login
      state: query
